[package]
name        = "rustsec-admin"
description = "Admin utility for maintaining the RustSec Advisory Database"
version     = "0.8.2"
authors     = ["Tony Arcieri <bascule@gmail.com>"]
license     = "Apache-2.0 OR MIT"
homepage    = "https://rustsec.org"
repository  = "https://github.com/RustSec/rustsec/tree/main/admin"
readme      = "README.md"
edition     = "2018"

[dependencies]
abscissa_core = "0.6"
askama = "0.11"
atom_syndication = "0.11"
chrono = { version = "0.4", default-features = false, features = ["clock"]  }
clap = "4"
comrak = { version = "0.14", default-features = false }
crates-index = "0.18"
rust-embed = "6.4"
rustsec = { version = "0.26", path = "../rustsec", features = ["osv-export"] }
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"
termcolor = "1"
thiserror = "1"
toml = "0.5"
xml-rs = "0.8"

[dev-dependencies]
abscissa_core = { version = "0.6", features = ["testing"] }
once_cell = "1.5"
